# Generated by Django 5.2.4 on 2025-10-30 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='grafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('x_axis_label', models.CharField(max_length=100)),
                ('y_axis_label', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, default='graficos/default.png', upload_to='graficos/')),
                ('obj3d', models.FileField(blank=True, default='objetos3d/default.obj', upload_to='objetos3d/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='valores_grafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_data', models.FloatField()),
                ('y_data', models.FloatField()),
                ('grafico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.grafico')),
            ],
        ),
    ]
